name: Publish to PyPi

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create distribution
      run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py sdist bdist_wheel

    - name: Publish to pypi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        # Password for your PyPI user or an access token
        password: ${{ secrets.pypi_password }}
