name: Publish to PyPi

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up git credentials
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Update version
      run: |
        echo ${{ steps.get_version.outputs.VERSION }} > VERSION
        git add VERSION
        git commit -m "Updated version to ${{ steps.get_version.outputs.VERSION }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create distribution
      run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py sdist bdist_wheel

    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        # Password for your PyPI user or an access token
        password: ${{ secrets.pypi_password }}
